language: rust
after_success: |
    cargo doc \
    && echo '<meta http-equiv=refresh content=0;url=serde_byte_repr/index.html>' > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
